### ISSUE TITLE
ReactJS & SEO - Stato dell'arte

### ISSUE THREAD

**Issue by salvoravida** [milanofrontend/talks#19]
## Titolo del Talk
ReactJS & SEO - Stato dell'arte

## Durata
da stimare

## Descrizione Twitter-sized (140 characters)
Soluzioni esistenti via SSR e non, principali pro e contro delle differenti soluzioni.

## Descrizione
Soluzioni esistenti via SSR e non, principali pro e contro delle differenti soluzioni.
Esempio di app reale in produzione con SEO e performance nei vari motori di ricerca. 
Futuro: cosa ci riserva? soluzioni in via di sviluppo non production ready.

**Comment by massimosiani** [comment]
Ha senso parlare di SEO e web components in questo talk? Almeno parzialmente.
Oppure introduciamo un altro talk a riguardo?

**Comment by salvoravida** [comment]
Potrebbe essere interessante un confronto con altre SPA / webcomp ma io lascerei il topic pricipale ReactJS.
