### ISSUE TITLE
Inspecting, debugging and profiling

### ISSUE THREAD

**Issue by gcmznt** [milanofrontend/talks#5]
## Titolo del Talk
Inspecting, debugging and profiling

## Durata
40 minuti

## Descrizione Twitter-sized (140 characters)
Vediamo in dettagli come funzionano i chrome devtools per analizzare le nostre pagine web

## Descrizione
Vediamo praticamente tab per tab come funzionano, a cosa servono e come interagire con gli strumenti offerti dal piu' diffuso browser di BigG

**Comment by bwlt** [comment]
Se andassimo direttamente al sodo per fare 40 minuti della tab `Performance` ? 🙃

**Comment by JinKanzaki90** [comment]
Sì, magari meno enfasi su Elements, Console e Sources e focalizzarsi più su Network, Performance & co. sarebbe preferibile. Bella idea comunque!

**Comment by gcmznt** [comment]
Direi che ha senso... anche perche' sono i tab che richiedono molte piu' spiegazioni

**Comment by alessiodionisi** [comment]
Io voto il focus sulla tab Performance e una spolverata veloce su Network

**Comment by ewanpayne** [comment]
voto anche io come alessio. Perfomance e Network.
